// import '@styles/globals.css';
// import ConditionalNavbar from '@components/navbar/ConditionalNavbar';
// import ConditionalFooter from '@components/footer/ConditionalFooter';
// import { AuthContextProvider } from '@context/AuthContext';

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
  
//   return (
//     <html lang="en">
//       <body>
//         <AuthContextProvider>
//          <ConditionalNavbar/>
//           {children}
//           {/* <ConditionalFooter/> */}
//         </AuthContextProvider>
//       </body>
//     </html>
//   );
// }

// RootLayout.js (Server Component)
import '@styles/globals.css';
import { AuthContextProvider } from '@context/AuthContext';
import { PromptProvider } from '@context/PromptContext';
import { ChatPromptProvider } from '@context/ChatPromptContext';
import { KeywordPromptProvider } from '@context/KeywordPromptContext';
import { CompetitorPromptProvider } from '@context/CompetitorPromptCount';
import ClientOnlyContent from './ClientOnlyContent';
import { ThemeProvider } from 'next-themes';
import {GoogleAnalytics} from '@next/third-parties/google'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <head>
      <script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GT-TX9GL6T5');`
          }}
        />
              <script
          dangerouslySetInnerHTML={{
            __html: `!function(f,b,e,v,n,t,s)
                    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                    n.queue=[];t=b.createElement(e);t.async=!0;
                    t.src=v;s=b.getElementsByTagName(e)[0];
                    s.parentNode.insertBefore(t,s)}(window, document,'script',
                    'https://connect.facebook.net/en_US/fbevents.js');
                    fbq('init', '690026023692369');
                    fbq('track', 'PageView');`
          }}
        />
      </head>
      
      <body>
       
        <AuthContextProvider>
          <PromptProvider>
            <KeywordPromptProvider>
              <CompetitorPromptProvider>
                <ChatPromptProvider>
            <ThemeProvider attribute="class">
                <ClientOnlyContent>{children}</ClientOnlyContent>
                <GoogleAnalytics gaId="G-RSWM44431B" />

                </ThemeProvider>
                </ChatPromptProvider>
                </CompetitorPromptProvider>
            </KeywordPromptProvider>
          </PromptProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
