// import '@styles/globals.css';
// import ConditionalNavbar from '@components/navbar/ConditionalNavbar';
// import ConditionalFooter from '@components/footer/ConditionalFooter';
// import { AuthContextProvider } from '@context/AuthContext';

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
  
//   return (
//     <html lang="en">
//       <body>
//         <AuthContextProvider>
//          <ConditionalNavbar/>
//           {children}
//           {/* <ConditionalFooter/> */}
//         </AuthContextProvider>
//       </body>
//     </html>
//   );
// }

// RootLayout.js (Server Component)
import '@styles/globals.css';
import { AuthContextProvider } from '@context/AuthContext';
import { PromptProvider } from '@context/PromptContext';
import { ChatPromptProvider } from '@context/ChatPromptContext';
import { KeywordPromptProvider } from '@context/KeywordPromptContext';
import { CompetitorPromptProvider } from '@context/CompetitorPromptCount';
import ClientOnlyContent from './ClientOnlyContent';
import { ThemeProvider } from 'next-themes';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <head>
      <script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','G-WBCYM89TML');`
          }}
        />
      </head>
      <body>
       
        <AuthContextProvider>
          <PromptProvider>
            <KeywordPromptProvider>
              <CompetitorPromptProvider>
                <ChatPromptProvider>
            <ThemeProvider attribute="class">
                <ClientOnlyContent>{children}</ClientOnlyContent>
                </ThemeProvider>
                </ChatPromptProvider>
                </CompetitorPromptProvider>
            </KeywordPromptProvider>
          </PromptProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
